services:
  postgres:
    image: postgres:16-alpine
    container_name: doc_fn_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-doc_fn}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
